### ISSUE TITLE
pgcapture extension also parse temp table

### ISSUE THREAD

**Issue by KennyChenFight** [replicase/pgcapture#71]
Hi @rjuju 
The issue now is that the pgcapture extension is capturing queries related to temp tables that PostgreSQL itself creates (for example, during REFRESH MATERIALIZED VIEW). 
See below example：
```sql
postgres=# select id, query, tags from pgcapture.ddl_logs order by id desc limit 3;
28 | DROP TABLE pg_temp_827.pg_temp_20855_2, pg_temp_827.pg_temp_20855                    | {"DROP TABLE"}
27 | ALTER TABLE pg_temp_827.pg_temp_20855_2 ADD COLUMN newdata pg_temp_827.pg_temp_20855 | {"ALTER TABLE"}
26 | CREATE TEMP TABLE pg_temp_827.pg_temp_20855_2 (tid pg_catalog.tid)                   | {"CREATE TABLE"}
```

This causes the downstream PostgreSQL to receive the same event, leading to errors such as 'temp table does not exist.' What would be a good way to filter out this type of query?
Do you suggest any good solution? thx!

**Comment by rjuju** [comment]
I will work on a fix for that soon (I'm traveling around for the national day holiday).

it should be straightforward to handle most of the commands, but DROP is a bit more tricky as you can drop both regular and temp tables in the same command. it can be handled too though (I actually already fixed that problem in some internal extension at work).

**Comment by KennyChenFight** [comment]
> I will work on a fix for that soon (I'm traveling around for the national day holiday).
> 
> it should be straightforward to handle most of the commands, but DROP is a bit more tricky as you can drop both regular and temp tables in the same command. it can be handled too though (I actually already fixed that problem in some internal extension at work).

I am looking forward to! thx again!

**Comment by rjuju** [comment]
I just sent a PR to ignore queries touching temp tables and properly dealing with DROP.  As mentioned in the commit, some DDL could technically cause problem, but I don't think that anyone will run a GRANT on a temporary table or add a comment.  Let me know if you still prefer to handle them.  I might of course have missed other DDL, if that happens of course I will fix it.  While on that topic, isn't the current behavior possibly ambiguous?  For DDL on unqualified relation without the search_path it should be quite easy to end up replaying the DDL on the wrong object, if you use the same object in multiple schemas.

Finally, I didn't add explicit test for a REFRESH MATERIALIZED VIEW CONCURRENTLY, but did check manually to ensure that the internally generated command where excluded, the same way as they are with explicit queries.
